hpcf<-"/Users/Thakur24/Desktop/Exploratory data analysis/household_power_consumption.txt"
hpc<-read.table(hpcf, header=TRUE , sep=";" , stringsAsFactors=FALSE , dec=".")
head(hpc)
reqhpcdata<-hpc[hpc$Date %in% c("1/2/2007","2/2/2007") ,]
Date_Time<-strptime(paste(reqhpcdata$Date,reqhpcdata$Time,sep=" "), "%d/%m/%Y %H:%M:%S")
Global_Active_Power<-as.numeric(reqhpcdata$Global_active_power)
Sub_Metering_1<-as.numeric(reqhpcdata$Sub_metering_1)
Sub_Metering_2<-as.numeric(reqhpcdata$Sub_metering_2)
Sub_Metering_3<-as.numeric(reqhpcdata$Sub_metering_3)
png("plot3.png",width=480,height=480)
plot(Date_Time,Sub_Metering_1,type="l",ylab="Energy sub metering")
lines(Date_Time,Sub_Metering_2,type="l",col="red")
lines(Date_Time,Sub_Metering_3,type="l",col="blue")
legend("topright",c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"),lty=1,lwd=2.5,col=c("black","red","blue"))
dev.off()